# ──────────────────────────────────────────────
# docker-compose.local.yml — Override para probar
# producción localmente (sin dnsmasq, en localhost)
# ──────────────────────────────────────────────
services:
  nginx:
    build:
      args:
        NGINX_CONF: nginx.conf.local

  dnsmasq:
    profiles:
      - skip

  backend:
    environment:
      CORS_ALLOW_ALL_ORIGINS: "True"
      DJANGO_ALLOWED_HOSTS: "localhost,backend"
