# Generated by Django 6.0.5 on 2026-05-28 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_number', models.IntegerField(choices=[(1, 'Primera'), (2, 'Segunda'), (3, 'Tercera')])),
                ('created_in', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='persons.person')),
            ],
            options={
                'verbose_name': 'Llamada',
                'verbose_name_plural': 'Llamadas',
                'db_table': 'Call',
                'unique_together': {('person', 'call_number')},
            },
        ),
        migrations.CreateModel(
            name='CallDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('date_made', models.DateTimeField(blank=True, null=True)),
                ('made', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, choices=[('effective', 'Efectivo'), ('not_effective', 'No Efectivo')], max_length=20, null=True)),
                ('annotation', models.TextField(blank=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='call_signatures/')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='calls.call')),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_details', to='accounts.adviser')),
            ],
            options={
                'verbose_name': 'Detalle de Llamada',
                'verbose_name_plural': 'Detalles de Llamada',
                'db_table': 'call_details',
            },
        ),
    ]
