# Generated by Django 6.0.5 on 2026-05-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='theme',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro')], default='light', max_length=10),
        ),
    ]
