# Generated by Django 6.0.5 on 2026-06-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_registeruser_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='advisers_m2m', to='accounts.role'),
        ),
    ]
