# Generated by Django 6.0.5 on 2026-06-01 21:00

from django.db import migrations


def copy_roles(apps, schema_editor):
    Adviser = apps.get_model('accounts', 'Adviser')
    for adviser in Adviser.objects.all():
        if adviser.role_id:
            adviser.roles.add(adviser.role_id)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_adviser_roles'),
    ]

    operations = [
        migrations.RunPython(copy_roles, migrations.RunPython.noop),
    ]
