# Generated by Django 6.0.5 on 2026-06-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_copy_role_to_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adviser',
            name='role',
        ),
        migrations.AlterField(
            model_name='adviser',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='advisers', to='accounts.role'),
        ),
    ]
