# Generated by Django 6.0.5 on 2026-05-28 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=13, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('pending', 'Pendiente'), ('assigned', 'Asignado'), ('unassigned', 'Sin Asignar'), ('effective', 'Efectivo'), ('not_effective', 'No Efectivo')], default='pending', max_length=20)),
                ('comes_from', models.CharField(choices=[('other_church', 'Viene de otra iglesia cristiana'), ('young', 'Joven'), ('normal', 'Normal'), ('distance', 'Distancia')], default='normal', max_length=20)),
                ('comes_from_church', models.CharField(blank=True, max_length=100, null=True)),
                ('comes_from_details', models.TextField(blank=True, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='person_signatures/')),
                ('is_young', models.BooleanField(default=False)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('enrollment_fund_1', models.BooleanField(default=False)),
                ('baptized', models.BooleanField(default=False)),
                ('church_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.churchservice')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.neighborhood')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_persons', to='accounts.adviser')),
                ('spiritual_father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spiritual_children', to='accounts.adviser')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'Person',
            },
        ),
    ]
