# Generated by Django 6.0.5 on 2026-05-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_person_is_from_other_church'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_from_other_church',
        ),
        migrations.AlterField(
            model_name='person',
            name='comes_from',
            field=models.CharField(blank=True, choices=[('other_church', 'Viene de otra iglesia cristiana')], default='', max_length=20),
        ),
    ]
