# Generated by Django 6.0.5 on 2026-05-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_remove_person_is_from_other_church_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='comes_from',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_young',
        ),
        migrations.AddField(
            model_name='person',
            name='specialism',
            field=models.CharField(choices=[('joven', 'Joven'), ('normal', 'Normal'), ('other_church', 'Otra Iglesia'), ('distance', 'Distancia')], default='normal', max_length=20),
        ),
    ]
