# Generated by Django 6.0.5 on 2026-05-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_convert_unassigned_to_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='data_consent',
            field=models.BooleanField(default=False, verbose_name='Consentimiento de datos'),
        ),
        migrations.AlterField(
            model_name='person',
            name='assignment_state',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('assigned', 'Asignado'), ('completed', 'Completado')], default='pending', max_length=20),
        ),
    ]
