# Generated by Django 6.0.5 on 2026-05-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_person_data_consent_alter_person_assignment_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='person_photos/'),
        ),
    ]
