# Generated by Django 6.0.5 on 2026-06-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0009_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
