# Generated by Django 6.0.5 on 2026-06-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0010_person_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='assignment_state',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('assigned', 'Asignado'), ('completed', 'Completado'), ('deactivated', 'Desactivado')], default='pending', max_length=20),
        ),
    ]
