# Generated by Django 6.0.5 on 2026-05-28 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Acudiente',
                'verbose_name_plural': 'Acudientes',
                'db_table': 'Attendant',
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('hour', models.TimeField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Calendario',
                'verbose_name_plural': 'Calendarios',
                'db_table': 'Calendar',
            },
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Modalidad',
                'verbose_name_plural': 'Modalidades',
                'db_table': 'Mode',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='baptisms.calendar')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='accounts.adviser')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='baptisms.mode')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'db_table': 'Class',
            },
        ),
        migrations.CreateModel(
            name='BaptismalRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('baptism_decision', models.CharField(choices=[('yes', 'Sí'), ('no', 'No'), ('undecided', 'Indeciso')], default='undecided', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='baptism_photos/')),
                ('shirt_size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5)),
                ('time_in_church', models.CharField(blank=True, max_length=100)),
                ('baptized', models.BooleanField(default=False)),
                ('details', models.TextField(blank=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('attendant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baptisms.attendant')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baptismal_registers', to='persons.person')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baptismal_registers', to='accounts.adviser')),
                ('class_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baptismal_registers', to='baptisms.class')),
            ],
            options={
                'verbose_name': 'Registro Bautismal',
                'verbose_name_plural': 'Registros Bautismales',
                'db_table': 'baptismal register',
            },
        ),
    ]
