# Generated by Django 6.0.5 on 2026-05-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptisms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptismalregister',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
