# Generated by Django 6.0.5 on 2026-05-30 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baptisms', '0002_baptism_age_nullable'),
        ('persons', '0009_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendant',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendants', to='persons.person'),
        ),
    ]
