# Generated by Django 6.0 on 2026-05-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('12h', '12 horas antes'), ('6h', '6 horas antes'), ('3h', '3 horas antes')], max_length=5)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Fallido')], default='sent', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('call_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='calls.calldetail')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'Notification',
                'unique_together': {('call_detail', 'notification_type')},
            },
        ),
    ]
