# Generated by Django 6.0.5 on 2026-05-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('aviso_1', 'Primer aviso (50%)'), ('aviso_2', 'Segundo aviso (25%)'), ('aviso_3', 'Tercer aviso (12.5%)')], max_length=8),
        ),
    ]
